//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 07:04:17 DE CET 
//


package parser.serverData.tribeRelation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tribe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tribe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggro" type="{}TribeListType" minOccurs="0"/>
 *         &lt;element name="hostile" type="{}TribeListType" minOccurs="0"/>
 *         &lt;element name="friend" type="{}TribeListType" minOccurs="0"/>
 *         &lt;element name="neutral" type="{}TribeListType" minOccurs="0"/>
 *         &lt;element name="support" type="{}TribeListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="base" type="{}TribeClass" />
 *       &lt;attribute name="name" use="required" type="{}TribeClass" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tribe", propOrder = {
    "aggro",
    "hostile",
    "friend",
    "neutral",
    "support"
})
public class Tribe {

    @XmlList
    protected List<TribeClass> aggro;
    @XmlList
    protected List<TribeClass> hostile;
    @XmlList
    protected List<TribeClass> friend;
    @XmlList
    protected List<TribeClass> neutral;
    @XmlList
    protected List<TribeClass> support;
    @XmlAttribute
    protected TribeClass base;
    @XmlAttribute(required = true)
    protected TribeClass name;

    /**
     * Gets the value of the aggro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<TribeClass> getAggro() {
        if (aggro == null) {
            aggro = new ArrayList<TribeClass>();
        }
        return this.aggro;
    }

    /**
     * Gets the value of the hostile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<TribeClass> getHostile() {
        if (hostile == null) {
            hostile = new ArrayList<TribeClass>();
        }
        return this.hostile;
    }

    /**
     * Gets the value of the friend property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the friend property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFriend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<TribeClass> getFriend() {
        if (friend == null) {
            friend = new ArrayList<TribeClass>();
        }
        return this.friend;
    }

    /**
     * Gets the value of the neutral property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neutral property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeutral().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<TribeClass> getNeutral() {
        if (neutral == null) {
            neutral = new ArrayList<TribeClass>();
        }
        return this.neutral;
    }

    /**
     * Gets the value of the support property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the support property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<TribeClass> getSupport() {
        if (support == null) {
            support = new ArrayList<TribeClass>();
        }
        return this.support;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public TribeClass getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(TribeClass value) {
        this.base = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public TribeClass getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(TribeClass value) {
        this.name = value;
    }

}
