//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.20 at 04:53:03 DU CEST 
//


package parser.serverData.tribeRelation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tribe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tribe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggro" type="{}Aggro" minOccurs="0"/>
 *         &lt;element name="hostile" type="{}Hostile" minOccurs="0"/>
 *         &lt;element name="friend" type="{}Friend" minOccurs="0"/>
 *         &lt;element name="neutral" type="{}Neutral" minOccurs="0"/>
 *         &lt;element name="support" type="{}Support" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="base" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tribe", propOrder = {
    "aggro",
    "hostile",
    "friend",
    "neutral",
    "support"
})
public class Tribe {

    protected Aggro aggro;
    protected Hostile hostile;
    protected Friend friend;
    protected Neutral neutral;
    protected Support support;
    @XmlAttribute
    protected String base;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the aggro property.
     * 
     * @return
     *     possible object is
     *     {@link Aggro }
     *     
     */
    public Aggro getAggro() {
        return aggro;
    }

    /**
     * Sets the value of the aggro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aggro }
     *     
     */
    public void setAggro(Aggro value) {
        this.aggro = value;
    }

    /**
     * Gets the value of the hostile property.
     * 
     * @return
     *     possible object is
     *     {@link Hostile }
     *     
     */
    public Hostile getHostile() {
        return hostile;
    }

    /**
     * Sets the value of the hostile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hostile }
     *     
     */
    public void setHostile(Hostile value) {
        this.hostile = value;
    }

    /**
     * Gets the value of the friend property.
     * 
     * @return
     *     possible object is
     *     {@link Friend }
     *     
     */
    public Friend getFriend() {
        return friend;
    }

    /**
     * Sets the value of the friend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Friend }
     *     
     */
    public void setFriend(Friend value) {
        this.friend = value;
    }

    /**
     * Gets the value of the neutral property.
     * 
     * @return
     *     possible object is
     *     {@link Neutral }
     *     
     */
    public Neutral getNeutral() {
        return neutral;
    }

    /**
     * Sets the value of the neutral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Neutral }
     *     
     */
    public void setNeutral(Neutral value) {
        this.neutral = value;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link Support }
     *     
     */
    public Support getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Support }
     *     
     */
    public void setSupport(Support value) {
        this.support = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
