//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.20 at 07:25:49 DU CEST 
//

package parser.serverData.tribeRelation;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>Java class for tribeClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tribeClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PC"/>
 *     &lt;enumeration value="LIGHT_SUR_MOB"/>
 *     &lt;enumeration value="LIGHT_LICH"/>
 *     &lt;enumeration value="GENERAL"/>
 *     &lt;enumeration value="GUARD"/>
 *     &lt;enumeration value="DUMMY"/>
 *     &lt;enumeration value="DUMMY2"/>
 *     &lt;enumeration value="PC_DARK"/>
 *     &lt;enumeration value="DARK_SUR_MOB"/>
 *     &lt;enumeration value="DARK_LICH"/>
 *     &lt;enumeration value="FIELD_OBJECT_ALL"/>
 *     &lt;enumeration value="GENERAL_DARK"/>
 *     &lt;enumeration value="GUARD_DARK"/>
 *     &lt;enumeration value="PC_DRAGON"/>
 *     &lt;enumeration value="GENERAL_DRAGON"/>
 *     &lt;enumeration value="GUARD_DRAGON"/>
 *     &lt;enumeration value="MONSTER"/>
 *     &lt;enumeration value="POLYMORPHPARROT"/>
 *     &lt;enumeration value="PET"/>
 *     &lt;enumeration value="PET_DARK"/>
 *     &lt;enumeration value="AGGRESSIVESINGLEMONSTER"/>
 *     &lt;enumeration value="AGGRESSIVESUPPORTMONSTER"/>
 *     &lt;enumeration value="FRILLFAIMAMCOUPLE"/>
 *     &lt;enumeration value="SPAKY"/>
 *     &lt;enumeration value="FUNGUS"/>
 *     &lt;enumeration value="MUTA"/>
 *     &lt;enumeration value="ORC"/>
 *     &lt;enumeration value="GOBLIN"/>
 *     &lt;enumeration value="POLYMORPHFUNGY"/>
 *     &lt;enumeration value="QUESTGUARD_DARK"/>
 *     &lt;enumeration value="FUNGY"/>
 *     &lt;enumeration value="BRAX"/>
 *     &lt;enumeration value="HIPPOLIZARD"/>
 *     &lt;enumeration value="FRILLFAIMAMBABY"/>
 *     &lt;enumeration value="FRILLFAIMAMMOM"/>
 *     &lt;enumeration value="FETHLOT"/>
 *     &lt;enumeration value="GARGOYLE"/>
 *     &lt;enumeration value="MINX"/>
 *     &lt;enumeration value="ZAIF"/>
 *     &lt;enumeration value="TOG"/>
 *     &lt;enumeration value="GUARD_D1NOATTACK"/>
 *     &lt;enumeration value="ZAIF_ATOG"/>
 *     &lt;enumeration value="TOG_AZAIF"/>
 *     &lt;enumeration value="ZAIF_AMINX"/>
 *     &lt;enumeration value="MINX_HZAIF"/>
 *     &lt;enumeration value="MERDION"/>
 *     &lt;enumeration value="GUARDIAN"/>
 *     &lt;enumeration value="DARU"/>
 *     &lt;enumeration value="LUPYLLINI"/>
 *     &lt;enumeration value="MOSBEARBABY"/>
 *     &lt;enumeration value="MOSBEARFATHER"/>
 *     &lt;enumeration value="SOULEDSTONE"/>
 *     &lt;enumeration value="SOULEDSTONE_MINI"/>
 *     &lt;enumeration value="MINX_HKALNIF"/>
 *     &lt;enumeration value="KALNIF_AMINX"/>
 *     &lt;enumeration value="KALNIF_ATOG"/>
 *     &lt;enumeration value="TOG_AKALNIF"/>
 *     &lt;enumeration value="FARMER_HKERUBIM_LF1"/>
 *     &lt;enumeration value="KERUBIM_AFARMER_LF1"/>
 *     &lt;enumeration value="GUARD_LIGHT_AKERUBIM_LF1"/>
 *     &lt;enumeration value="D1_HKERUBIM_LF1"/>
 *     &lt;enumeration value="KERUBIM_AD1_LF1"/>
 *     &lt;enumeration value="BROWNIE"/>
 *     &lt;enumeration value="KRALL"/>
 *     &lt;enumeration value="BROWNIECOWARD"/>
 *     &lt;enumeration value="BROWNIEGUARD"/>
 *     &lt;enumeration value="BROWNIEFELLER_HZAIF_LF1"/>
 *     &lt;enumeration value="ZAIF_ABROWNIEFELLER_LF1"/>
 *     &lt;enumeration value="KRALLMASTER"/>
 *     &lt;enumeration value="KRALL_TRAINING"/>
 *     &lt;enumeration value="KRALLWIZARDCY"/>
 *     &lt;enumeration value="CYCLOPSBOSS"/>
 *     &lt;enumeration value="TARGETBASFELT_DF1"/>
 *     &lt;enumeration value="SPRIGG_HROBBERALDER_DF1"/>
 *     &lt;enumeration value="ROBBERALDER_ASPRIGG_DF1"/>
 *     &lt;enumeration value="SPRIGGREFUSE_DF1"/>
 *     &lt;enumeration value="ARCHERYBASFELT_ATARGETBASFELT_DF1"/>
 *     &lt;enumeration value="ARCHERYBASFELT_ATARGETBASFELT_LF1"/>
 *     &lt;enumeration value="ARCHERYBASFELT2_ATARGETBASFELT2_DF1"/>
 *     &lt;enumeration value="TARGETBASFELT2_DF1"/>
 *     &lt;enumeration value="ARCHERYBASFELT2_ATARGETBASFELT2_LF1"/>
 *     &lt;enumeration value="GUARD_FTARGETBASFELT_DF1"/>
 *     &lt;enumeration value="GUARD_FTARGETBASFELT_LF1"/>
 *     &lt;enumeration value="LYCAN"/>
 *     &lt;enumeration value="LYCAN_MAGE"/>
 *     &lt;enumeration value="LYCAN_PET"/>
 *     &lt;enumeration value="LYCAN_HUNTER"/>
 *     &lt;enumeration value="RATMANWORKER"/>
 *     &lt;enumeration value="LYCANMASTER"/>
 *     &lt;enumeration value="TOWERMAN"/>
 *     &lt;enumeration value="LYCAN_AGUARD_DARK_DF1"/>
 *     &lt;enumeration value="LYCAN_TRAINING"/>
 *     &lt;enumeration value="GUARD_DARK_ALYCANARATMAN_DF1"/>
 *     &lt;enumeration value="LYCAN_PET_TRAINING"/>
 *     &lt;enumeration value="LYCAN_SUM"/>
 *     &lt;enumeration value="LYCANDF2MASTER"/>
 *     &lt;enumeration value="LYCANDF2SLAVE1"/>
 *     &lt;enumeration value="LYCANDF2SLAVE2"/>
 *     &lt;enumeration value="RATMAN"/>
 *     &lt;enumeration value="SAMM"/>
 *     &lt;enumeration value="RATMAN_AGUARD_DARK_DF1"/>
 *     &lt;enumeration value="RATMANDFWORKER"/>
 *     &lt;enumeration value="UNDEADGRADIATOR_DF1"/>
 *     &lt;enumeration value="GUARD_LIGHTMA"/>
 *     &lt;enumeration value="GUARD_DARKMA"/>
 *     &lt;enumeration value="GUARD_DRAGONMA"/>
 *     &lt;enumeration value="NEUT"/>
 *     &lt;enumeration value="NEUTQUEEN"/>
 *     &lt;enumeration value="NEUTBUG"/>
 *     &lt;enumeration value="AGGRESSIVE_LIGHT"/>
 *     &lt;enumeration value="AGGRESSIVE_DARK"/>
 *     &lt;enumeration value="AGGRESSIVE_DRAGON"/>
 *     &lt;enumeration value="ABDRAGON_AABDARK"/>
 *     &lt;enumeration value="ABDARK_AABDRAGON"/>
 *     &lt;enumeration value="OCTASIDEBABY"/>
 *     &lt;enumeration value="GUARD_DARKAENEMY"/>
 *     &lt;enumeration value="ENEMY_AGUARD_DARK"/>
 *     &lt;enumeration value="GRIFFO"/>
 *     &lt;enumeration value="GRIFFON"/>
 *     &lt;enumeration value="SHELLIZARDMOM"/>
 *     &lt;enumeration value="SHELLIZARDBABY"/>
 *     &lt;enumeration value="MANDURITWEAK"/>
 *     &lt;enumeration value="CHERUBIM2ND"/>
 *     &lt;enumeration value="LEHPAR"/>
 *     &lt;enumeration value="LEHPAR_AGUARDDARK"/>
 *     &lt;enumeration value="LEHPAR_APRETOR"/>
 *     &lt;enumeration value="GUARDDARK_ALEHPAR"/>
 *     &lt;enumeration value="AGGRESSIVE1_AAGGRESSIVE2"/>
 *     &lt;enumeration value="AGGRESSIVE2_AAGGRESSIVE1"/>
 *     &lt;enumeration value="PRETOR_ALEHPAR"/>
 *     &lt;enumeration value="FIREELBOSS"/>
 *     &lt;enumeration value="FIREEL1"/>
 *     &lt;enumeration value="FIREEL2"/>
 *     &lt;enumeration value="FIREEL3"/>
 *     &lt;enumeration value="AIRELBOSS"/>
 *     &lt;enumeration value="AIREL1"/>
 *     &lt;enumeration value="AIREL2"/>
 *     &lt;enumeration value="AIREL3"/>
 *     &lt;enumeration value="ETTIN"/>
 *     &lt;enumeration value="L_DRGUARD_ADRAGGMOB1"/>
 *     &lt;enumeration value="DRAGGMOB_ADRGUARD1"/>
 *     &lt;enumeration value="DARU_HZAIF"/>
 *     &lt;enumeration value="ZAIF_ADARU"/>
 *     &lt;enumeration value="MUTA_HOCTASIDE"/>
 *     &lt;enumeration value="OCTASIDE_AMUTA"/>
 *     &lt;enumeration value="LIZARDMAN"/>
 *     &lt;enumeration value="ATAURIC"/>
 *     &lt;enumeration value="AHELLHOUND"/>
 *     &lt;enumeration value="APRETOR"/>
 *     &lt;enumeration value="GHOSTLIGHT"/>
 *     &lt;enumeration value="GHOSTDARK"/>
 *     &lt;enumeration value="BMLGUARDIAN"/>
 *     &lt;enumeration value="BMDGUARDIAN"/>
 *     &lt;enumeration value="GMASTER"/>
 *     &lt;enumeration value="GSLAVE"/>
 *     &lt;enumeration value="ELEMENTAL_FIRE"/>
 *     &lt;enumeration value="ELEMENTAL_EARTH"/>
 *     &lt;enumeration value="ELEMENTAL_AIR"/>
 *     &lt;enumeration value="ELEMENTAL_WATER"/>
 *     &lt;enumeration value="BAT_FAMILY_ELITE"/>
 *     &lt;enumeration value="SUCCUBUS_ELITE"/>
 *     &lt;enumeration value="SAM_ELITE"/>
 *     &lt;enumeration value="GARGOYLE_ELITE"/>
 *     &lt;enumeration value="MAIDENGOLEM_ELITE"/>
 *     &lt;enumeration value="AGGRESSIVE_LIGHT_HSPECTRE"/>
 *     &lt;enumeration value="SPECTRE_AALIGHTDARK"/>
 *     &lt;enumeration value="AGGRESSIVE_DARK_HSPECTRE"/>
 *     &lt;enumeration value="DRAMA_EVE_NONPC_A"/>
 *     &lt;enumeration value="DRAMA_EVE_NONPC_B"/>
 *     &lt;enumeration value="DRAMA_KIMEIA_NPC"/>
 *     &lt;enumeration value="DRAMA_KIMEIA_MOB"/>
 *     &lt;enumeration value="DRAMA_EVE_NONPC_DARKA"/>
 *     &lt;enumeration value="DRAMA_EVE_NONPC_DARKB"/>
 *     &lt;enumeration value="DRAMA_KIMEIA_DARKNPC"/>
 *     &lt;enumeration value="XIPETO"/>
 *     &lt;enumeration value="XIPETOBABY"/>
 *     &lt;enumeration value="TAURIC"/>
 *     &lt;enumeration value="CRESTLICH"/>
 *     &lt;enumeration value="NNAGA"/>
 *     &lt;enumeration value="NLIZARDMAN"/>
 *     &lt;enumeration value="NLIZARDRAISER"/>
 *     &lt;enumeration value="NLIZARDPET"/>
 *     &lt;enumeration value="NLIZARDPRIEST"/>
 *     &lt;enumeration value="NNAGA_PRIEST"/>
 *     &lt;enumeration value="NNAGA_ELEMENTALIST"/>
 *     &lt;enumeration value="NNAGA_PRIESTBOSS"/>
 *     &lt;enumeration value="XDRAKAN"/>
 *     &lt;enumeration value="XDRAKAN_ELEMENTALIST"/>
 *     &lt;enumeration value="XDRAKAN_PRIEST"/>
 *     &lt;enumeration value="DRAGON"/>
 *     &lt;enumeration value="NNAGA_SERVANT"/>
 *     &lt;enumeration value="NNAGA_ELEMENTAL"/>
 *     &lt;enumeration value="NLIZARDMAN2"/>
 *     &lt;enumeration value="NNAGA_BOSS_SERVANT"/>
 *     &lt;enumeration value="SEIREN_MASTER"/>
 *     &lt;enumeration value="SEIREN_SNAKE"/>
 *     &lt;enumeration value="SEIREN"/>
 *     &lt;enumeration value="GENERAL_ADADR"/>
 *     &lt;enumeration value="F4RAID"/>
 *     &lt;enumeration value="GENERALDA_ALIDR"/>
 *     &lt;enumeration value="GENERALDR_ALIDA"/>
 *     &lt;enumeration value="LIZARDMAN_BOMB"/>
 *     &lt;enumeration value="BOMB_LIZARDMAN"/>
 *     &lt;enumeration value="LIZARDMAN_KB"/>
 *     &lt;enumeration value="DRAKEPURPLE_MASTER"/>
 *     &lt;enumeration value="DRAKEPURPLE_SLAVE"/>
 *     &lt;enumeration value="DRAKY_BOMB_MASTER"/>
 *     &lt;enumeration value="DRAKY_BOMB_EX"/>
 *     &lt;enumeration value="FIREFUNGY"/>
 *     &lt;enumeration value="NOFIGHT"/>
 *     &lt;enumeration value="DRAKANDF3BOSS"/>
 *     &lt;enumeration value="DRAKANDF3SLAVE"/>
 *     &lt;enumeration value="CONSIADE"/>
 *     &lt;enumeration value="CONSIADE_SUM"/>
 *     &lt;enumeration value="PARENTSMONSTER"/>
 *     &lt;enumeration value="CHILDMONSTER"/>
 *     &lt;enumeration value="TEST_LIGHT_ADARK"/>
 *     &lt;enumeration value="TEST_LIGHT_ADRAGON"/>
 *     &lt;enumeration value="TEST_LIGHT_AETC"/>
 *     &lt;enumeration value="TEST_DARK_ALIGHT"/>
 *     &lt;enumeration value="TEST_DARK_ADRAGON"/>
 *     &lt;enumeration value="TEST_DARK_AETC"/>
 *     &lt;enumeration value="TEST_DRAGON_ALIGHT"/>
 *     &lt;enumeration value="TEST_DRAGON_ADARK"/>
 *     &lt;enumeration value="TEST_DRAGON_AETC"/>
 *     &lt;enumeration value="TEST_ETC_ALIGHT"/>
 *     &lt;enumeration value="TEST_ETC_ADARK"/>
 *     &lt;enumeration value="TEST_ETC_ADRAGON"/>
 *     &lt;enumeration value="ABYSSDRAKANGATE"/>
 *     &lt;enumeration value="DARK_NPC"/>
 *     &lt;enumeration value="LICH_SOULEDSTONE"/>
 *     &lt;enumeration value="DARK_MOB"/>
 *     &lt;enumeration value="LIGHT_NPC"/>
 *     &lt;enumeration value="LIGHT_MOB"/>
 *     &lt;enumeration value="LIGHT_DENLABIS"/>
 *     &lt;enumeration value="FIRETEMPLE_MOB"/>
 *     &lt;enumeration value="QUESTGUARD_LIGHT"/>
 *     &lt;enumeration value="BROHUM"/>
 *     &lt;enumeration value="CALYDON"/>
 *     &lt;enumeration value="CALYDON_POLYMORPH"/>
 *     &lt;enumeration value="SWELLFISH"/>
 *     &lt;enumeration value="TRICON"/>
 *     &lt;enumeration value="TRICO"/>
 *     &lt;enumeration value="PROTECTGUARD_LIGHT"/>
 *     &lt;enumeration value="PROTECTGUARD_DARK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TribeClass
{

	PC(0),
	LIGHT_SUR_MOB(1),
	LIGHT_LICH(2),
	GENERAL(3),
	GUARD(4),
	DUMMY(5),
	DUMMY2(6),
	PC_DARK(7),
	DARK_SUR_MOB(8),
	DARK_LICH(9),
	FIELD_OBJECT_ALL(10),
	GENERAL_DARK(11),
	GUARD_DARK(12),
	PC_DRAGON(13),
	GENERAL_DRAGON(14),
	GUARD_DRAGON(15),
	MONSTER(16),
	POLYMORPHPARROT(17),
	PET(18),
	PET_DARK(19),
	AGGRESSIVESINGLEMONSTER(20),
	AGGRESSIVESUPPORTMONSTER(21),
	FRILLFAIMAMCOUPLE(22),
	SPAKY(23),
	FUNGUS(24),
	MUTA(25),
	ORC(26),
	GOBLIN(27),
	POLYMORPHFUNGY(28),
	QUESTGUARD_DARK(29),
	FUNGY(30),
	BRAX(31),
	HIPPOLIZARD(32),
	FRILLFAIMAMBABY(33),
	FRILLFAIMAMMOM(34),
	FETHLOT(35),
	GARGOYLE(36),
	MINX(37),
	ZAIF(38),
	TOG(39),
	GUARD_D1NOATTACK(40),
	ZAIF_ATOG(41),
	TOG_AZAIF(42),
	ZAIF_AMINX(43),
	MINX_HZAIF(44),
	MERDION(45),
	GUARDIAN(46),
	DARU(47),
	LUPYLLINI(48),
	MOSBEARBABY(49),
	MOSBEARFATHER(50),
	SOULEDSTONE(51),
	SOULEDSTONE_MINI(52),
	MINX_HKALNIF(53),
	KALNIF_AMINX(54),
	KALNIF_ATOG(55),
	TOG_AKALNIF(56),
	FARMER_HKERUBIM_LF1(57),
	KERUBIM_AFARMER_LF1(58),
	GUARD_LIGHT_AKERUBIM_LF1(59),
	D1_HKERUBIM_LF1(60),
	KERUBIM_AD1_LF1(61),
	BROWNIE(62),
	KRALL(63),
	BROWNIECOWARD(64),
	BROWNIEGUARD(65),
	BROWNIEFELLER_HZAIF_LF1(66),
	ZAIF_ABROWNIEFELLER_LF1(67),
	KRALLMASTER(68),
	KRALL_TRAINING(69),
	KRALLWIZARDCY(70),
	CYCLOPSBOSS(71),
	TARGETBASFELT_DF1(72),
	SPRIGG_HROBBERALDER_DF1(73),
	ROBBERALDER_ASPRIGG_DF1(74),
	SPRIGGREFUSE_DF1(75),
	ARCHERYBASFELT_ATARGETBASFELT_DF1(76),
	ARCHERYBASFELT_ATARGETBASFELT_LF1(77),
	ARCHERYBASFELT2_ATARGETBASFELT2_DF1(78),
	TARGETBASFELT2_DF1(79),
	ARCHERYBASFELT2_ATARGETBASFELT2_LF1(80),
	GUARD_FTARGETBASFELT_DF1(81),
	GUARD_FTARGETBASFELT_LF1(82),
	LYCAN(83),
	LYCAN_MAGE(84),
	LYCAN_PET(85),
	LYCAN_HUNTER(86),
	RATMANWORKER(87),
	LYCANMASTER(88),
	TOWERMAN(89),
	LYCAN_AGUARD_DARK_DF1(90),
	LYCAN_TRAINING(91),
	GUARD_DARK_ALYCANARATMAN_DF1(92),
	LYCAN_PET_TRAINING(93),
	LYCAN_SUM(94),
	LYCANDF2MASTER(95),
	LYCANDF2SLAVE1(96),
	LYCANDF2SLAVE2(97),
	RATMAN(98),
	SAMM(99),
	RATMAN_AGUARD_DARK_DF1(100),
	RATMANDFWORKER(101),
	UNDEADGRADIATOR_DF1(102),
	GUARD_LIGHTMA(103),
	GUARD_DARKMA(104),
	GUARD_DRAGONMA(105),
	NEUT(106),
	NEUTQUEEN(107),
	NEUTBUG(108),
	AGGRESSIVE_LIGHT(109),
	AGGRESSIVE_DARK(110),
	AGGRESSIVE_DRAGON(111),
	ABDRAGON_AABDARK(112),
	ABDARK_AABDRAGON(113),
	OCTASIDEBABY(114),
	GUARD_DARKAENEMY(115),
	ENEMY_AGUARD_DARK(116),
	GRIFFO(117),
	GRIFFON(118),
	SHELLIZARDMOM(119),
	SHELLIZARDBABY(120),
	MANDURITWEAK(121),
	CHERUBIM2ND(122),
	LEHPAR(123),
	LEHPAR_AGUARDDARK(124),
	LEHPAR_APRETOR(125),
	GUARDDARK_ALEHPAR(126),
	AGGRESSIVE1_AAGGRESSIVE2(127),
	AGGRESSIVE2_AAGGRESSIVE1(128),
	PRETOR_ALEHPAR(129),
	FIREELBOSS(130),
	FIREEL1(131),
	FIREEL2(132),
	FIREEL3(133),
	AIRELBOSS(134),
	AIREL1(135),
	AIREL2(136),
	AIREL3(137),
	ETTIN(138),
	L_DRGUARD_ADRAGGMOB1(139),
	DRAGGMOB_ADRGUARD1(140),
	DARU_HZAIF(141),
	ZAIF_ADARU(142),
	MUTA_HOCTASIDE(143),
	OCTASIDE_AMUTA(144),
	LIZARDMAN(145),
	ATAURIC(146),
	AHELLHOUND(147),
	APRETOR(148),
	GHOSTLIGHT(149),
	GHOSTDARK(150),
	BMLGUARDIAN(151),
	BMDGUARDIAN(152),
	GMASTER(153),
	GSLAVE(154),
	ELEMENTAL_FIRE(155),
	ELEMENTAL_EARTH(156),
	ELEMENTAL_AIR(157),
	ELEMENTAL_WATER(158),
	BAT_FAMILY_ELITE(159),
	SUCCUBUS_ELITE(160),
	SAM_ELITE(161),
	GARGOYLE_ELITE(162),
	MAIDENGOLEM_ELITE(163),
	AGGRESSIVE_LIGHT_HSPECTRE(164),
	SPECTRE_AALIGHTDARK(165),
	AGGRESSIVE_DARK_HSPECTRE(166),
	DRAMA_EVE_NONPC_A(167),
	DRAMA_EVE_NONPC_B(168),
	DRAMA_KIMEIA_NPC(169),
	DRAMA_KIMEIA_MOB(170),
	DRAMA_EVE_NONPC_DARKA(171),
	DRAMA_EVE_NONPC_DARKB(172),
	DRAMA_KIMEIA_DARKNPC(173),
	XIPETO(174),
	XIPETOBABY(175),
	TAURIC(176),
	CRESTLICH(177),
	NNAGA(178),
	NLIZARDMAN(179),
	NLIZARDRAISER(180),
	NLIZARDPET(181),
	NLIZARDPRIEST(182),
	NNAGA_PRIEST(183),
	NNAGA_ELEMENTALIST(184),
	NNAGA_PRIESTBOSS(185),
	XDRAKAN(186),
	XDRAKAN_ELEMENTALIST(187),
	XDRAKAN_PRIEST(188),
	DRAGON(189),
	NNAGA_SERVANT(190),
	NNAGA_ELEMENTAL(191),
	NLIZARDMAN2(192),
	NNAGA_BOSS_SERVANT(193),
	SEIREN_MASTER(194),
	SEIREN_SNAKE(195),
	SEIREN(196),
	GENERAL_ADADR(197),
	F4RAID(198),
	GENERALDA_ALIDR(199),
	GENERALDR_ALIDA(200),
	LIZARDMAN_BOMB(201),
	BOMB_LIZARDMAN(202),
	LIZARDMAN_KB(203),
	DRAKEPURPLE_MASTER(204),
	DRAKEPURPLE_SLAVE(205),
	DRAKY_BOMB_MASTER(206),
	DRAKY_BOMB_EX(207),
	FIREFUNGY(208),
	NOFIGHT(209),
	FIELD_OBJECT_LIGHT(210),
	DRAKANDF3BOSS(211),
	DRAKANDF3SLAVE(212),
	CONSIADE(213),
	CONSIADE_SUM(214),
	PARENTSMONSTER(215),
	CHILDMONSTER(216),
	TEST_LIGHT_ADARK(217),
	TEST_LIGHT_ADRAGON(218),
	TEST_LIGHT_AETC(219),
	TEST_DARK_ALIGHT(220),
	TEST_DARK_ADRAGON(221),
	TEST_DARK_AETC(222),
	TEST_DRAGON_ALIGHT(223),
	TEST_DRAGON_ADARK(224),
	TEST_DRAGON_AETC(225),
	TEST_ETC_ALIGHT(226),
	TEST_ETC_ADARK(227),
	TEST_ETC_ADRAGON(228),
	ABYSSDRAKANGATE(229),
	DARK_NPC(230),
	LICH_SOULEDSTONE(231),
	DARK_MOB(232),
	LIGHT_NPC(233),
	LIGHT_MOB(234),
	LIGHT_DENLABIS(235),
	FIRETEMPLE_MOB(236),
	QUESTGUARD_LIGHT(237),
	BROHUM(238),
	CALYDON(239),
	CALYDON_POLYMORPH(240),
	SWELLFISH(241),
	TRICON(242),
	TRICO(243),
	PROTECTGUARD_LIGHT(244),
	PROTECTGUARD_DARK(245),
	FIELD_OBJECT_ALL_MONSTER(246),
	HOLYSERVANT(247),
	HOLYSERVANT_DEBUFFER(248),
	USEALL(249),
	HOLYSERVANT_DESPAWN(250),
	RANMARK(251),
	AGGRESSIVESUPPORTMONSTER2(252),
	LASBERG(253),
	SHULACK(254),
	AGGRESSIVETOSHULACK2(255),
	SHULACK_ATTACKED(256),
	SHULACK_DECK(257),
	SHULACK_ATTACKING(258),
	SHULACK_SUPPORT(259),
	ESCORT(260),
	AGGRESSIVEESCORT(261),
	IDCATACOMBS_TAROS(262),
	XDRAKAN_PET(263),
	XDRAKAN_SERVANT(264),
	AGGRESSIVETOSHULACK(265),
	SHULACK_DECK_KILLER(266),
	DRAGON_SLAVE(267),
	SPALLER(268),
	SPALLERCTRL(269),
	SHULACK_SLAVE(270),
	IDLF1_MONSTER(271),
	AGGRESSIVETOPCPET(272),
	GENERALDR_ALIDA_SUPPORT(273),
	GOLEM_SWITCH(274),
	USEALLNONETOMONSTER(275),
	FANATIC(276),
	IDTEMPLE_BUGS(277),
	IDTEMPLE_STONE(278),
	IDELIM(279),
	AGGRESSIVETOIDELIM(280),
	IDELIM_FRIEND(281),
	FRIENDLYTOIDELIM(282),
	IDCATACOMBS_DRAKE(283),
	IDCATACOMBS_DRAKE_SUM(284),
	HOSTILE_ALL(285),
	AGGRESSIVE_ALL(286),
	F4GUARD_LIGHT(287),
	F4GUARD_DARK(288),
	F4GUARD_DRAGON(289),
	DRAMATA(290),
	DRAMATATIMERA(291),
	DRAMATATIMERB(292),
	DRAKANPOLYMORPH(293),
	DRAKANDOOR(294),
	GHTIMER(295),
	DUMMY_DGUARD(296),
	DUMMY2_DGUARD(297),
	CRYSTAL(298),
	ANTI_CRYSTAL(299),
	CRYSTAL_NMDD(300),
	DUMMY_LGUARD(301),
	DUMMY2_LGUARD(302),
	HOSTILEONLYMONSTER(303),
	ATKDRAKAN(304),
	CRYSTAL_SUM(305);

	private final int	value;

	TribeClass(int v)
	{
		value = v;
	}

	public int value()
	{
		return value;
	}
}
