//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 05:57:01 DU CET 
//

package parser.clientData.clientNpc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for BoundRadius complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BoundRadius">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="front" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="side" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="upper" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundRadius", propOrder =
{ "front", "side", "upper" })
public class BoundRadius
{

	protected float	front;
	protected float	side;
	protected float	upper;

	/**
	 * Gets the value of the front property.
	 * 
	 */
	public float getFront()
	{
		return front;
	}

	/**
	 * Sets the value of the front property.
	 * 
	 */
	public void setFront(float value)
	{
		this.front = value;
	}

	/**
	 * Gets the value of the side property.
	 * 
	 */
	public float getSide()
	{
		return side;
	}

	/**
	 * Sets the value of the side property.
	 * 
	 */
	public void setSide(float value)
	{
		this.side = value;
	}

	/**
	 * Gets the value of the upper property.
	 * 
	 */
	public float getUpper()
	{
		return upper;
	}

	/**
	 * Sets the value of the upper property.
	 * 
	 */
	public void setUpper(float value)
	{
		this.upper = value;
	}

}
