//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 05:57:01 DU CET 
//


package parser.clientData.clientNpc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="buy_price_rate" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="atab" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctab" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="etab" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tab" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Data", propOrder = {
    "buyPriceRate",
    "atab",
    "ctab",
    "etab",
    "tab"
})
public class Data {

    @XmlElement(name = "buy_price_rate", required = true)
    protected BigInteger buyPriceRate;
    @XmlElement(required = true)
    protected String atab;
    @XmlElement(required = true)
    protected String ctab;
    @XmlElement(required = true)
    protected String etab;
    @XmlElement(required = true)
    protected String tab;

    /**
     * Gets the value of the buyPriceRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuyPriceRate() {
        return buyPriceRate;
    }

    /**
     * Sets the value of the buyPriceRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuyPriceRate(BigInteger value) {
        this.buyPriceRate = value;
    }

    /**
     * Gets the value of the atab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtab() {
        return atab;
    }

    /**
     * Sets the value of the atab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtab(String value) {
        this.atab = value;
    }

    /**
     * Gets the value of the ctab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtab() {
        return ctab;
    }

    /**
     * Sets the value of the ctab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtab(String value) {
        this.ctab = value;
    }

    /**
     * Gets the value of the etab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtab() {
        return etab;
    }

    /**
     * Sets the value of the etab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtab(String value) {
        this.etab = value;
    }

    /**
     * Gets the value of the tab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTab() {
        return tab;
    }

    /**
     * Sets the value of the tab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTab(String value) {
        this.tab = value;
    }

}
