//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 05:57:01 DU CET 
//

package parser.clientData.clientNpc;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parser.clientData.clientNpc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parser.clientData.clientNpc
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link VisibleEquipments }
	 * 
	 */
	public VisibleEquipments createVisibleEquipments()
	{
		return new VisibleEquipments();
	}

	/**
	 * Create an instance of {@link TradeInfo }
	 * 
	 */
	public TradeInfo createTradeInfo()
	{
		return new TradeInfo();
	}

	/**
	 * Create an instance of {@link NpcClients }
	 * 
	 */
	public NpcClients createNpcClients()
	{
		return new NpcClients();
	}

	/**
	 * Create an instance of {@link TabList }
	 * 
	 */
	public TabList createTabList()
	{
		return new TabList();
	}

	/**
	 * Create an instance of {@link Data }
	 * 
	 */
	public Data createData()
	{
		return new Data();
	}

	/**
	 * Create an instance of {@link Appearance }
	 * 
	 */
	public Appearance createAppearance()
	{
		return new Appearance();
	}

	/**
	 * Create an instance of {@link BoundRadius }
	 * 
	 */
	public BoundRadius createBoundRadius()
	{
		return new BoundRadius();
	}

	/**
	 * Create an instance of {@link NpcClient }
	 * 
	 */
	public NpcClient createNpcClient()
	{
		return new NpcClient();
	}

}
