//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 05:57:01 DU CET 
//

package parser.clientData.clientNpc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TabList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TabList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{}Data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TabList", propOrder =
{ "data" })
public class TabList
{

	@XmlElement(required = true)
	protected Data	data;

	/**
	 * Gets the value of the data property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Data }
	 *     
	 */
	public Data getData()
	{
		return data;
	}

	/**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Data }
	 *     
	 */
	public void setData(Data value)
	{
		this.data = value;
	}

}
