//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 05:57:01 DU CET 
//

package parser.clientData.clientNpc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TradeInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tab_list" type="{}TabList" minOccurs="0"/>
 *         &lt;element name="sell_price_rate" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="buy_price_rate" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeInfo", propOrder =
{ "tabList", "sellPriceRate", "buyPriceRate" })
public class TradeInfo
{

	@XmlElement(name = "tab_list")
	protected TabList		tabList;
	@XmlElement(name = "sell_price_rate")
	protected BigInteger	sellPriceRate;
	@XmlElement(name = "buy_price_rate")
	protected BigInteger	buyPriceRate;

	/**
	 * Gets the value of the tabList property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link TabList }
	 *     
	 */
	public TabList getTabList()
	{
		return tabList;
	}

	/**
	 * Sets the value of the tabList property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link TabList }
	 *     
	 */
	public void setTabList(TabList value)
	{
		this.tabList = value;
	}

	/**
	 * Gets the value of the sellPriceRate property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *     
	 */
	public BigInteger getSellPriceRate()
	{
		return sellPriceRate;
	}

	/**
	 * Sets the value of the sellPriceRate property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *     
	 */
	public void setSellPriceRate(BigInteger value)
	{
		this.sellPriceRate = value;
	}

	/**
	 * Gets the value of the buyPriceRate property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *     
	 */
	public BigInteger getBuyPriceRate()
	{
		return buyPriceRate;
	}

	/**
	 * Sets the value of the buyPriceRate property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *     
	 */
	public void setBuyPriceRate(BigInteger value)
	{
		this.buyPriceRate = value;
	}

}
