//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.29 at 08:46:27 DE CET 
//


package parser.serverData.spawns;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parser.serverData.spawns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parser.serverData.spawns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpawnGroup.Object }
     * 
     */
    public SpawnGroup.Object createSpawnGroupObject() {
        return new SpawnGroup.Object();
    }

    /**
     * Create an instance of {@link Spawns }
     * 
     */
    public Spawns createSpawns() {
        return new Spawns();
    }

    /**
     * Create an instance of {@link SpawnGroup }
     * 
     */
    public SpawnGroup createSpawnGroup() {
        return new SpawnGroup();
    }

}
