//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.29 at 08:46:27 DE CET 
//


package parser.serverData.spawns;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpawnGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpawnGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="z" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="h" type="{}Heading" />
 *                 &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="rw" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="staticid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="fly" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="time" type="{}SpawnTime" />
 *       &lt;attribute name="anchor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="handler" type="{}SpawnHandlerType" />
 *       &lt;attribute name="interval" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="npcid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="map" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rw" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="siegeid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="race" type="{}SiegeRace" />
 *       &lt;attribute name="protector" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="stype" type="{}SiegeSpawnType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpawnGroup", propOrder = {
    "object"
})
public class SpawnGroup {

    protected List<SpawnGroup.Object> object;
    @XmlAttribute
    protected SpawnTime time;
    @XmlAttribute
    protected String anchor;
    @XmlAttribute
    protected SpawnHandlerType handler;
    @XmlAttribute
    protected Integer interval;
    @XmlAttribute
    protected Integer pool;
    @XmlAttribute
    protected Integer npcid;
    @XmlAttribute
    protected Integer map;
    @XmlAttribute
    protected Integer rw;
    @XmlAttribute
    protected Integer siegeid;
    @XmlAttribute
    protected SiegeRace race;
    @XmlAttribute
    protected Boolean protector;
    @XmlAttribute
    protected SiegeSpawnType stype;

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpawnGroup.Object }
     * 
     * 
     */
    public List<SpawnGroup.Object> getObject() {
        if (object == null) {
            object = new ArrayList<SpawnGroup.Object>();
        }
        return this.object;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link SpawnTime }
     *     
     */
    public String getTime() {
    	if (time == null)
    		return "ALL";
        return time.toString();
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpawnTime }
     *     
     */
    public void setTime(SpawnTime value) {
        this.time = value;
    }

    /**
     * Gets the value of the anchor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchor() {
        return anchor;
    }

    /**
     * Sets the value of the anchor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchor(String value) {
        this.anchor = value;
    }

    /**
     * Gets the value of the handler property.
     * 
     * @return
     *     possible object is
     *     {@link SpawnHandlerType }
     *     
     */
    public SpawnHandlerType getHandler() {
        return handler;
    }

    /**
     * Sets the value of the handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpawnHandlerType }
     *     
     */
    public void setHandler(SpawnHandlerType value) {
        this.handler = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInterval(Integer value) {
        this.interval = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPool(Integer value) {
        this.pool = value;
    }

    /**
     * Gets the value of the npcid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNpcid() {
        return npcid;
    }

    /**
     * Sets the value of the npcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNpcid(Integer value) {
        this.npcid = value;
    }

    /**
     * Gets the value of the map property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMap() {
        return map;
    }

    /**
     * Sets the value of the map property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMap(Integer value) {
        this.map = value;
    }

    /**
     * Gets the value of the rw property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRw() {
        return rw;
    }

    /**
     * Sets the value of the rw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRw(Integer value) {
        this.rw = value;
    }

    /**
     * Gets the value of the siegeid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSiegeid() {
    	if (siegeid == null)
    		return 0;
        return siegeid;
    }

    /**
     * Sets the value of the siegeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSiegeid(Integer value) {
        this.siegeid = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link SiegeRace }
     *     
     */
    public SiegeRace getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiegeRace }
     *     
     */
    public void setRace(SiegeRace value) {
        this.race = value;
    }

    /**
     * Gets the value of the protector property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProtector() {
        return protector;
    }

    /**
     * Sets the value of the protector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProtector(Boolean value) {
        this.protector = value;
    }

    /**
     * Gets the value of the stype property.
     * 
     * @return
     *     possible object is
     *     {@link SiegeSpawnType }
     *     
     */
    public SiegeSpawnType getStype() {
        return stype;
    }

    /**
     * Sets the value of the stype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiegeSpawnType }
     *     
     */
    public void setStype(SiegeSpawnType value) {
        this.stype = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="z" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="h" type="{}Heading" />
     *       &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="rw" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="staticid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="fly" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Object {

        @XmlAttribute
        protected Float x;
        @XmlAttribute
        protected Float y;
        @XmlAttribute
        protected Float z;
        @XmlAttribute
        protected Byte h;
        @XmlAttribute
        protected Integer w;
        @XmlAttribute
        protected Integer rw;
        @XmlAttribute
        protected Integer staticid;
        @XmlAttribute
        protected Integer fly;

        /**
         * Gets the value of the x property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setX(Float value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setY(Float value) {
            this.y = value;
        }

        /**
         * Gets the value of the z property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getZ() {
            return z;
        }

        /**
         * Sets the value of the z property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setZ(Float value) {
            this.z = value;
        }

        /**
         * Gets the value of the h property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getH() {
            return h;
        }

        /**
         * Sets the value of the h property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setH(Byte value) {
            this.h = value;
        }

        /**
         * Gets the value of the w property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getW() {
            return w;
        }

        /**
         * Sets the value of the w property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setW(Integer value) {
            this.w = value;
        }

        /**
         * Gets the value of the rw property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRw() {
            return rw;
        }

        /**
         * Sets the value of the rw property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRw(Integer value) {
            this.rw = value;
        }

        /**
         * Gets the value of the staticid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getStaticid() {
        	if (staticid == null)
        		return 0;
            return staticid;
        }

        /**
         * Sets the value of the staticid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setStaticid(Integer value) {
            this.staticid = value;
        }

        /**
         * Gets the value of the fly property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFly() {
            return fly;
        }

        /**
         * Sets the value of the fly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFly(Integer value) {
            this.fly = value;
        }

    }

}
