//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.20 at 05:33:46 DU CEST 
//

package parser.clientData.tribeRelation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Tribe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tribe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="base_tribe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="friendly" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="none" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aggressive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="support" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="neutral" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Tribe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tribe", propOrder =
{ "baseTribe", "friendly", "none", "aggressive", "support", "hostile", "neutral" })
public class Tribe
{

	@XmlElement(name = "base_tribe", required = true)
	protected String	baseTribe;
	@XmlElement(required = true)
	protected String	friendly;
	@XmlElement(required = true)
	protected String	none;
	@XmlElement(required = true)
	protected String	aggressive;
	@XmlElement(required = true)
	protected String	support;
	@XmlElement(required = true)
	protected String	hostile;
	@XmlElement(required = true)
	protected String	neutral;
	@XmlAttribute(name = "Tribe")
	protected String	tribe;

	/**
	 * Gets the value of the baseTribe property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getBaseTribe()
	{
		return baseTribe;
	}

	/**
	 * Sets the value of the baseTribe property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setBaseTribe(String value)
	{
		this.baseTribe = value;
	}

	/**
	 * Gets the value of the friendly property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getFriendly()
	{
		return friendly;
	}

	/**
	 * Sets the value of the friendly property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setFriendly(String value)
	{
		this.friendly = value;
	}

	/**
	 * Gets the value of the none property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNone()
	{
		return none;
	}

	/**
	 * Sets the value of the none property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNone(String value)
	{
		this.none = value;
	}

	/**
	 * Gets the value of the aggressive property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getAggressive()
	{
		return aggressive;
	}

	/**
	 * Sets the value of the aggressive property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setAggressive(String value)
	{
		this.aggressive = value;
	}

	/**
	 * Gets the value of the support property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getSupport()
	{
		return support;
	}

	/**
	 * Sets the value of the support property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setSupport(String value)
	{
		this.support = value;
	}

	/**
	 * Gets the value of the hostile property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getHostile()
	{
		return hostile;
	}

	/**
	 * Sets the value of the hostile property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setHostile(String value)
	{
		this.hostile = value;
	}

	/**
	 * Gets the value of the neutral property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNeutral()
	{
		return neutral;
	}

	/**
	 * Sets the value of the neutral property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNeutral(String value)
	{
		this.neutral = value;
	}

	/**
	 * Gets the value of the tribe property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getTribe()
	{
		return tribe;
	}

	/**
	 * Sets the value of the tribe property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setTribe(String value)
	{
		this.tribe = value;
	}

}
