//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:57:07 DE CET 
//

package parser.clientData.mission;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parser.clientData.mission package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parser.clientData.mission
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link EntityClass }
	 * 
	 */
	public EntityClass createEntityClass()
	{
		return new EntityClass();
	}

	/**
	 * Create an instance of {@link ObjectsClass }
	 * 
	 */
	public ObjectsClass createObjectsClass()
	{
		return new ObjectsClass();
	}

	/**
	 * Create an instance of {@link FlyingZone }
	 * 
	 */
	public FlyingZone createFlyingZone()
	{
		return new FlyingZone();
	}

	/**
	 * Create an instance of {@link SubZones }
	 * 
	 */
	public SubZones createSubZones()
	{
		return new SubZones();
	}

	/**
	 * Create an instance of {@link Mission }
	 * 
	 */
	public Mission createMission()
	{
		return new Mission();
	}

	/**
	 * Create an instance of {@link Data }
	 * 
	 */
	public Data createData()
	{
		return new Data();
	}

	/**
	 * Create an instance of {@link FlyingZones }
	 * 
	 */
	public FlyingZones createFlyingZones()
	{
		return new FlyingZones();
	}

	/**
	 * Create an instance of {@link ObjectClass }
	 * 
	 */
	public ObjectClass createObjectClass()
	{
		return new ObjectClass();
	}

	/**
	 * Create an instance of {@link Properties }
	 * 
	 */
	public Properties createProperties()
	{
		return new Properties();
	}

	/**
	 * Create an instance of {@link CommonShapeList }
	 * 
	 */
	public CommonShapeList createCommonShapeList()
	{
		return new CommonShapeList();
	}

	/**
	 * Create an instance of {@link SubZone }
	 * 
	 */
	public SubZone createSubZone()
	{
		return new SubZone();
	}

	/**
	 * Create an instance of {@link Points }
	 * 
	 */
	public Points createPoints()
	{
		return new Points();
	}

	/**
	 * Create an instance of {@link PointsInfo }
	 * 
	 */
	public PointsInfo createPointsInfo()
	{
		return new PointsInfo();
	}

}
