//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 05:57:07 DE CET 
//


package parser.clientData.mission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Properties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Properties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fileLadderCGF" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gostring_Text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Properties")
public class Properties {

    @XmlAttribute
    protected String fileLadderCGF;
    @XmlAttribute(name = "gostring_Text")
    protected String gostringText;

    /**
     * Gets the value of the fileLadderCGF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLadderCGF() {
        return fileLadderCGF;
    }

    /**
     * Sets the value of the fileLadderCGF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLadderCGF(String value) {
        this.fileLadderCGF = value;
    }

    /**
     * Gets the value of the gostringText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGostringText() {
        return gostringText;
    }

    /**
     * Sets the value of the gostringText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGostringText(String value) {
        this.gostringText = value;
    }

}
