//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 07:16:56 DU CET 
//

package parser.serverData.warehouseExpander;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parser.serverData.warehouseExpander package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName	_WarehouseExpander_QNAME	= new QName("", "warehouse_expander");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parser.serverData.warehouseExpander
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link Import }
	 * 
	 */
	public Import createImport()
	{
		return new Import();
	}

	/**
	 * Create an instance of {@link WarehouseExpand }
	 * 
	 */
	public WarehouseExpand createWarehouseExpand()
	{
		return new WarehouseExpand();
	}

	/**
	 * Create an instance of {@link WarehouseNpcTemplate }
	 * 
	 */
	public WarehouseNpcTemplate createWarehouseNpcTemplate()
	{
		return new WarehouseNpcTemplate();
	}

	/**
	 * Create an instance of {@link WarehouseExpander }
	 * 
	 */
	public WarehouseExpander createWarehouseExpander()
	{
		return new WarehouseExpander();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link WarehouseExpander }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "warehouse_expander")
	public JAXBElement<WarehouseExpander> createWarehouseExpander(WarehouseExpander value)
	{
		return new JAXBElement<WarehouseExpander>(_WarehouseExpander_QNAME, WarehouseExpander.class, null, value);
	}

}
